#!/bin/sh

JAVA_HOME=/usr
CLASSPATH="$(find /europa/lib/ -name '*.jar' | xargs echo | tr ' ' ':')"
JVM_ARGS="-Duser.timezone=UTC -Xmx2000M -Xms2000M"
$JAVA_HOME/bin/java $JVM_ARGS -cp $CLASSPATH com.distelli.europa.Europa --stage "$STAGE" --port 5050 --log-to-console $@
